spring:
  application:
    name: cms-vx

  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  devtools:
    restart:
      enabled: true
      additional-paths:
        - ../cms-web-templates/src/main/resources
        - ../cms-feature-auth/src/main/resources
        - ../cms-feature-person/src/main/resources
        - ../cms-feature-documents/src/main/resources
        - ../cms-feature-liturgy/src/main/resources
        - ../cms-feature-privacy/src/main/resources
        - ../cms-feature-audit/src/main/resources
        - ../cms-feature-finance/src/main/resources
        - ../cms-feature-workflow/src/main/resources
        - ../cms-feature-task/src/main/resources
        - ../cms-feature-events/src/main/resources
        - ../cms-feature-notifications/src/main/resources
        - ../cms-feature-homepage/src/main/resources
    livereload:
      enabled: true

  datasource:
    url: jdbc:mariadb://29753-44055.pph-server.de:3306/pgm_cms?useUnicode=true&connectionCollation=utf8mb4_unicode_ci&sslMode=DISABLED
    username: software
    password: GYdSQUW4fc0Dwh88
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000        # 10min
      connection-timeout: 30000   # 30s
      max-lifetime: 1800000       # 30min

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true
      # dein UUID-Fix
      hibernate.type.preferred_uuid_jdbc_type: CHAR

server:
  port: 9101
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: baxmc006
    key-store-type: PKCS12
    key-alias: localhost
  servlet:
    session:
      timeout: 30m
      cookie:
        name: CentralManagementSystem_vX
        http-only: true
        secure: true
        max-age: 86400

logging:
  file:
    path: ./cms_vx/logs

cms:
  notifications:
    push: fcm

notifications:
  fcm:
    enabled: true
    credentials: file:config/centralmanagementsystemx-04cd9f4980ad.json
    project-id: centralmanagementsystemx
